#Al entrar en isla, warp tierramedia
on join:
	wait 1 tick
	player is in "isla"
	execute console command "warp tierramedia %player%"
	stop

#Registro a un evento

command /evento [<text>] [<number>] [<text>] [<text>]:
	permission: skript.eventos
	permission message: &cNo tienes permiso para usar esta función.
	executable by: players and console
	trigger:
		if arg 1 is not set:
			message "Cupo &7%{evento.cupo}%&f / Evento &7%{evento.nombre}%&f / Línea 3 &7%{evento.lin3}%" to player
			message "Inscritos &7%{evento.inscritos::*}%" to player
			message "Suplentes &7%{suplentes.inscritos::*}%" to player
			message " " to player
			message "crear - borrar - llamar" to player
			#Copiar los inscritos a un .YML
			delete file "plugins/Skript/variables/eventos.yml"
			wait 1 tick
			loop {evento.inscritos::*}:
				# setListYML("evento.inscritos.principales" , "%loop-value%" , "../variables/eventos")
				add "%loop-value%" to yaml list "evento.inscritos.principales" from file "../variables/eventos.yml"
			loop {suplentes.inscritos::*}:				
				add "%loop-value%" to yaml list "evento.inscritos.suplentes" from file "../variables/eventos.yml"
			stop
		if arg 1 is "crear":
			set {evento.cupo} to arg 2
			set {evento.nombre} to arg 3
			set {evento.lin3} to arg 4
			wait 1 tick
			message "Cupo &7%{evento.cupo}%&f / Evento &7%{evento.nombre}%&f / Línea 3 &7%{evento.lin3}%" to player
			message "Crea un cartel E y dale clic derecho." to player
			message "Consulta evento con &a/evento&f y borralo con &a/evento borrar" to player
			log "%{evento.nombre}% - ABIERTO" to "eventos"
			stop
		if arg 1 is "llamar":
			loop {evento.inscritos::*}:
				execute player command "tp %loop-value% %player%"
				wait 20 ticks
		if arg 1 is "borrar":
			delete {evento.inscritos::*}
			delete {evento.cupo}
			delete {evento.nombre}
			delete {evento.lin3}
			wait 1 tick
			message "&cLos datos del evento han sido borrados." to player
			stop
		if arg 1 is "compilar":
			log "[PARTICIPANTES %{evento.nombre}%]%{evento.inscritos::*}%" to "eventos"
			log "[SUPLENTES %{evento.nombre}%]%{suplentes.inscritos::*}%" to "eventos"
			wait 5 ticks
			message " &aDatos compilados en el log." to player
			stop


on rightclick on sign:
	line 1 of the clicked block is "E":
		if player has permission "skript.eventos":
			set line 1 to "&1[Evento]"
			set line 2 to "%{evento.nombre}%"
			set line 3 to "%{evento.lin3}%"
			set line 4 to "&2%{evento.cupo}% cupos"
			wait 1 tick
			message "Cartel &1[Evento] &fcreado con éxito" to player
			stop
	
	line 1 of the clicked block is "&1[Evento]":
		if {evento.cupo} is greater than 0:
			if "%{evento.inscritos::*}%" contains "%player%":
				if player is holding any shovel:
					remove player from {evento.inscritos::*}
					add 1 to {evento.cupo}
					wait 1 tick
					log "%{evento.nombre}% - %player% RETIRADO" to "eventos"
					wait 1 tick
					message " " to player
					message " &aTe has retirado del evento." to player
					message " &7Si deseas volver a inscribirte, dale clic derecho al cartel sin tener una pala en tu mano." to player
					message " " to player
					wait 1 tick
					broadcast " &a&l%player% &ase ha retirado del evento &l%{evento.nombre}%&a. Quedan %{evento.cupo}% cupos."
					stop
				else:
					message " " to player
					message " &aYa estás registrado en este evento." to player
					message " &7Asegúrate de estar conectado en la fecha y hora del evento." to player
					message " " to player
					stop
			else:
				remove 1 from {evento.cupo}
				wait 1 tick
				log "%{evento.nombre}% - %player%" to "eventos"
				wait 1 tick
				message " " to player
				message " &e&l¡Felicidades %player%!" to player
				message " Te has registrado para &l%{evento.nombre}%" to player
				message " &7Asegúrate de estar conectado en la fecha y hora del evento. De lo cotrario, serás descalificado." to player
				message " " to player
				add player to {evento.inscritos::*}
				wait 20 ticks
				broadcast " &a&l%player% &ase ha registrado para el evento &l%{evento.nombre}%&a. Quedan %{evento.cupo}% cupos."
				stop
		else:
			if player is holding any shovel:
				remove player from {evento.inscritos::*}
				add 1 to {evento.cupo}
				wait 1 tick
				log "%{evento.nombre}% - %player% RETIRADO" to "eventos"
				wait 1 tick
				message " " to player
				message " &aTe has retirado del evento." to player
				message " &7Si deseas volver a inscribirte, dale clic derecho al cartel sin tener una pala en tu mano." to player
				message " " to player
				wait 1 tick
				broadcast " &a&l%player% &ase ha retirado del evento &l%{evento.nombre}%&a. Quedan %{evento.cupo}% cupos."
				stop
			else:
				message " &cLo sentimos. Ya no quedan cupos." to player
				message " &7Tendrás la oportunidad de participar en el siguiente evento." to player
				stop
		wait 10 ticks				
on rightclick on sign:
	line 1 of the clicked block is "&1[Evento]":
		wait 10 ticks
		if {evento.cupo} is greater than 0:
			set line 4 to "&2%{evento.cupo}% cupos"
			stop
		else:
			set line 4 to "&4Sin cupos"
			log "%{evento.nombre}% - CERRADO" to "eventos"
			stop
on leftclick on sign:
	line 1 of the clicked block is "&1[Evento]":
		message " &aInscripción al evento &l%{evento.nombre}%." to player
		if "%{evento.inscritos::*}%" contains "%player%":
			message " &7Ya estás inscrito." to player
			message " &7Si deseas retirarte haz clic derecho con cualquier pala en el cartel." to player
		else:
			if {evento.cupo} is greater than 0:
				message " &7Quedan %{evento.cupo}% cupos. Haz clic derecho para inscribirte." to player
			else:
				message " &cNo queda ningún cupo para inscribirse." to player


#Suplentes del evento

on rightclick on sign:
	line 1 of the clicked block is "S":
		if player has permission "skript.eventos":
			set line 1 to "&1[Suplentes]"
			set line 2 to "%{evento.nombre}%"
			set line 3 to "%{evento.lin3}%"
			#set line 4 to "&2%{suplentes.cupo}% cupos"
			wait 1 tick
			message "Cartel &1[Suplentes] &fcreado con éxito" to player
			stop
	
	line 1 of the clicked block is "&1[Suplentes]":
		if "%{evento.inscritos::*}%" contains "%player%":
			message " &7Ya estás inscrito en la lista de participantes del evento." to player
			message " &7No puedes registrarte en la lista de suplentes." to player
		else:
			if "%{suplentes.inscritos::*}%" contains "%player%":
				if player is holding any shovel:
					remove player from {suplentes.inscritos::*}
					wait 1 tick
					log "[SUPLENTE] %{evento.nombre}% - %player% RETIRADO" to "eventos"
					wait 1 tick
					message " " to player
					message " &aTe has retirado del la lista de suplentes." to player
					message " &7Si deseas volver a inscribirte, dale clic derecho al cartel sin tener una pala en tu mano." to player
					message " " to player
					wait 1 tick
					#broadcast " &a&l%player% &ase ha retirado de la lista de suplentes para &l%{suplentes.nombre}%&a. Quedan %{suplentes.cupo}% cupos."
					stop
				else:
					message " " to player
					message " &aYa estás registrado en la lista de suplentes." to player
					message " &7Asegúrate de estar conectado en la fecha y hora del evento por si falta algun participante inscrito." to player
					message " " to player
					stop
			else:
				log "[SUPLENTE] %{evento.nombre}% - %player%" to "eventos"
				wait 1 tick
				message " " to player
				message " Te has registrado en la lista de suplentes para &l%{evento.nombre}%" to player
				message " &7Asegúrate de estar conectado en la fecha y hora del evento por si falta algun participante inscrito." to player
				message " " to player
				add player to {suplentes.inscritos::*}
				wait 20 ticks
				#broadcast " &a&l%player% &ase ha registrado para el evento &l%{evento.nombre}%&a. Quedan %{evento.cupo}% cupos."
				stop      
on leftclick on sign:
	line 1 of the clicked block is "&1[Suplentes]":
		message " &aInscripción a la lista de suplentes del evento &l%{evento.nombre}%." to player
		if "%{suplentes.inscritos::*}%" contains "%player%":
			message " &7Ya estás inscrito." to player
			message " &7Si deseas retirarte haz clic derecho con cualquier pala en el cartel." to player
		else:
			message " &7Clic derecho para inscribirte como suplente." to player


#--------------------------------------------------------------------------------------
	

#Comandos Isla del tesoro
command /isla [<text>] [<number>]:
	permission: skript.eventos
	permission message: &cNo tienes permiso para usar esta función.
	executable by: players and console
	trigger:
		if arg 1 is not set:
			message "/isla tiempo <minutos>" to player
			message "/isla inicio" to player
			message "/isla final" to player
			message "/isla fuera" to player
			message "/isla lista" to player
		if arg 1 is set:
			if arg 1 is "tiempo":
				broadcast " "
				broadcast "<yellow><magic> !!<reset><yellow><bold> ISLA DEL TESORO <yellow><magic>!!"
				broadcast " La isla abrirá en <light red>%arg 2%<reset> minutos."
				broadcast " Vacía tu inventario y prepara tus mejores herramientas para venir a <light green>/warp isla<reset>."
				broadcast " "
				stop
			else if arg 1 is "inicio":
				execute console command "/pex group default add essentials.warps.isla"
				wait 1 second
				execute console command "/pex reload"
				wait 5 ticks
				broadcast " "
				broadcast "<yellow><magic> !!<reset><yellow><bold> ISLA DEL TESORO <yellow><magic>!!"
				broadcast " ¡LA ISLA HA ABIERTO!"
				broadcast " Ven con tus mejores herramientas a <light green>/warp isla<reset> en búsqueda de los mejores tesoros."
				broadcast " "
				stop
			else if arg 1 is "final":
				broadcast "<yellow><bold> ISLA DEL TESORO:<reset> La isla está próxima a cerrar. Aprovecha el tiempo que te queda."
				stop
			else if arg 1 is "fuera":
				broadcast "<yellow><bold> ISLA DEL TESORO:<reset> El evento ha terminado. La isla cerrará en <light red>1<reset> minuto."
				wait 55 seconds
				broadcast " Cerrando la isla en <light red>5<reset> segundos. Los jugadores en ella serán transportados a <light green>Tarazún<reset>."
				wait 5 seconds
				loop all players in "isla":
					execute console command "/mv tp %loop-player% tierramedia"
				execute console command "/pex group default remove essentials.warps.isla"
				wait 1 second
				execute console command "/pex reload"
				wait 5 seconds
				broadcast "<yellow><bold> ISLA DEL TESORO:<reset> La isla fue cerrada. Gracias por participar."
				stop
			else if arg 1 is "lista":
				message "Conectados en la isla:" to player
				wait 1 tick
				loop all players in "isla":
					message "- %loop-player%" to player
				stop

#Carteles de Isla del tesoro
on rightclick on sign:
	line 2 of the clicked block is "&l[Barco-Isla]":
		if player has the permission "skript.carteles":
			line 3 of the clicked block is "&2Abierto":
				message "Cerrando..." to player
				execute player command "fill -278 66 191 -278 66 191 fence"
				execute player command "fill -278 67 191 -278 67 191 wooden_slab"
				execute player command "fill -278 66 199 -278 66 199 fence"
				execute player command "fill -278 67 199 -278 67 199 wooden_slab"
				wait 15 tick
				execute player command "fill -279 66 191 -279 66 191 fence"
				execute player command "fill -279 67 191 -279 67 191 wooden_slab"
				execute player command "fill -279 66 199 -279 66 199 fence"
				execute player command "fill -279 67 199 -279 67 199 wooden_slab"
				wait 15 tick
				execute player command "fill -280 66 191 -280 66 191 fence"
				execute player command "fill -280 67 191 -280 67 191 wooden_slab"
				execute player command "fill -280 66 199 -280 66 199 fence"
				execute player command "fill -280 67 199 -280 67 199 wooden_slab"
				wait 15 tick
				execute player command "fill -281 66 191 -281 66 191 fence"
				execute player command "fill -281 67 191 -281 67 191 wooden_slab"
				execute player command "fill -281 66 199 -281 66 199 fence"
				execute player command "fill -281 67 199 -281 67 199 wooden_slab"
				wait 1 seconds
				set line 3 to "&4Cerrado"
				stop
			line 3 of the clicked block is "&4Cerrado":
				message "Abriendo..." to player
				execute player command "fill -281 66 191 -281 66 191 air"
				execute player command "fill -281 67 191 -281 67 191 air"
				execute player command "fill -281 66 199 -281 66 199 air"
				execute player command "fill -281 67 199 -281 67 199 air"
				execute player command "summon FireworksRocketEntity -290 62 167 {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:2,Flicker:0,Trail:1,Colors:[15435844,15790320],FadeColors:[4312372,15790320]}]}}}}"
				wait 15 tick
				execute player command "fill -280 66 191 -280 66 191 air"
				execute player command "fill -280 67 191 -280 67 191 air"
				execute player command "fill -280 66 199 -280 66 199 air"
				execute player command "fill -280 67 199 -280 67 199 air"
				execute player command "summon FireworksRocketEntity -268 62 202 {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:4,Flicker:0,Trail:1,Colors:[15435844,15790320],FadeColors:[11743532,4312372,15790320]}]}}}}"
				wait 15 tick
				execute player command "fill -279 66 191 -279 66 191 air"
				execute player command "fill -279 67 191 -279 67 191 air"
				execute player command "fill -279 66 199 -279 66 199 air"
				execute player command "fill -279 67 199 -279 67 199 air"
				execute player command "summon FireworksRocketEntity -263 62 173 {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Flicker:0,Trail:1,Colors:[15435844,15790320],FadeColors:[15790320]}]}}}}"
				wait 15 tick
				execute player command "fill -278 66 191 -278 66 191 air"
				execute player command "fill -278 67 191 -278 67 191 air"
				execute player command "fill -278 66 199 -278 66 199 air"
				execute player command "fill -278 67 199 -278 67 199 air"
				execute player command "summon FireworksRocketEntity -298 62 207 {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Flicker:0,Trail:1,Colors:[15435844,15790320],FadeColors:[15790320]}]}}}}"
				wait 1 seconds
				set line 3 to "&2Abierto"
				stop
		else:
			message "&cNo tienes permiso para usar esta función." to player
			stop

#Sólo admins pueden poner cofres en test o isla
on place of a chest:
	if world is "test" or "isla":
		if player don't have the permission "skript.admin":
			cancel event
			stop

#Cofres explosivos
on break of chest:
	if world is "test" or "isla":
		if player don't have the permission "skript.admin":
			cancel event

on rightclick on chest:
	if world is "test" or "isla":
		if player don't have the permission "skript.admin":
		#if player have the permission "skript.admin":  #dejar configurado el de arriba antes de cerrar.
			block contains tnt:
				clear the inventory of the block
				loop blocks in radius 5:
					if loop-block is a chest:
						set loop-block to air
				send player title "&4¡CORRE!" with subtitle "Morirás" for 2 seconds
				broadcast " &c&l%player% &cha detonado un cofre explosivo."
				wait 2 second		
				create an explosion of force 10 at event-location
				damage player by 9 hearts
			block contains emerald:
				broadcast " &a&l%player% &aha encontrado un ceitil."
				set {_efecto} to location of player
				spawn 1000 of particle happy villager offset by 2, 2, 2 at {_efecto}
				play raw sound "fireworks.launch" at player with pitch 1 volume 10
				log "%player% -> 1 ceitil" to "eventos"
			block contains nether star:
				broadcast " &a&l%player% &aha encontrado la estrella del inframundo."
				set {_efecto} to location of player
				spawn 1000 of particle happy villager offset by 2, 2, 2 at {_efecto}
				play raw sound "fireworks.launch" at player with pitch 1 volume 10
				log "%player% -> 1 estrella del inframundo" to "eventos"
			block contains bone named "zombie":
				clear the inventory of the block
				loop blocks in radius 5:
					if loop-block is a chest:
						set loop-block to air
				broadcast " &a&l%player% &aha invocado a &2Papá Zombie&a."
				set {_efecto} to location of player
				spawn 10 of particle large explode offset by 2, 2, 2 at {_efecto}
				play raw sound "random.explode" at player with pitch 1 volume 10
				spawn a zombie above the clicked block
				set the spawned zombie's display name to "&2Papá Zombie"
				set the spawned zombie's max health to 50
				heal the spawned zombie
				set helmet of spawned zombie to diamond helmet of protection 4 #with name "&eCasco de minero"
				set tool of spawned zombie to diamond sword of sharpness 3
				delete chestplate of spawned zombie
				delete leggings of spawned zombie
				delete boots of spawned zombie
				apply speed 1 to the spawned zombie for 9999 minutes
				apply resistance 3 to the spawned zombie for 9999 minutes
			block contains bone named "endermite":
				clear the inventory of the block
				loop blocks in radius 5:
					if loop-block is a chest:
						set loop-block to air
				broadcast " &a&l%player% &aha descubierto un nido de &5Endermites&a."
				set {_efecto} to location of player
				spawn 10 of particle large explode offset by 2, 2, 2 at {_efecto}
				play raw sound "random.explode" at player with pitch 1 volume 10
				spawn 20 endermites above the clicked block
				apply speed 2 to the spawned endermite for 9999 minutes
				apply resistance 3 to the spawned endermite for 9999 minutes
#			block contains bone named "creeper":
#				clear the inventory of the block
#				loop blocks in radius 5:
#					if loop-block is a chest:
#						set loop-block to air
#				#broadcast " &a&l%player% &aha invocado a &2Papá Zombie&a."
#				set {_efecto} to location of player
#				spawn 10 of particle large explode offset by 2, 2, 2 at {_efecto}
#				play raw sound "random.explode" at player with pitch 1 volume 10
#				spawn a creeper above the clicked block
#				spawn a spider above the clicked block
#				make the spawned creeper ride the spawned spider
#				set the spawned creeper's display name to "&2Jinete creeper"
#				set the spawned creeper's max health to 50
#				set the spawned spider's max health to 50
#				heal the spawned creeper
#				heal the spawned spider
#				set helmet of spawned creeper to diamond helmet of protection 4
#				set tool of spawned creeper to diamond sword of sharpness 3
#				apply speed 1 to the spawned spider for 9999 minutes
#				apply resistance 3 to the spawned spider for 9999 minutes

on death of a zombie:
	if victim is in "test" or "isla":
		if name of zombie contains "&2Papá Zombie":
			if attacker is a player:
				delete drops
				wait 1 tick
				drop diamond helmet of protection 4 with name "&2Casco de &2Papá Zombie" at victim's location
				drop diamond sword of sharpness 3 with name "&2Espada de &2Papá Zombie" at victim's location
				broadcast "&2Papá Zombie&a fue destruído por %attacker%"
				add 500 to the attacker's account
				send "&6Recibes &2$ &a500 &6por matar a &2Papá Zombie." to attacker

on death of a endermite:
	if victim is in "test" or "isla":
		if attacker is a player:
			add 50 to the attacker's account
			send "&6Recibes &2$ &a50 &6por matar un &5Endermite." to attacker


#Borra el cofre al cerrarlo
on rightclick on chest:
	if world is "test" or "isla":
		set {chest.%player%} to true
on inventory close:
	if world is "test" or "isla":
		if player don't have the permission "skript.admin":
			if {chest.%player%} is true:
				set {chest.%player%} to false
				loop blocks in radius 5:
					if loop-block is a chest:
						set loop-block to air



# No permitir comandos en la isla
on command:
	player is in "isla"
	player don't have the permission "skript.admin"
	if "%region at player%" contains "barco-isla":
		stop
	else if command is not "suicidarse","matarse","morir","morirse","msg","m","r","feed" or "yafue":
		cancel event
		send "&cNo puedes utilizar comandos aquí." to player
		stop
