options:
	denegado: "&f Las armas legendarias carecen de poderes en manos de un mortal. Sólo una &cDeidad &ftiene acceso a estos poderes."
	furia: "&6&lFuria de los cielos"
	arco: "&6&lArco del fin"

command /lore [<number>] [<text>]:
	permission: skript.admin
	trigger:
		if arg 1 is not set:
			message "/lore <linea> <texto>" to player
		if arg 1 is set:
			set line number arg of lore of player's tool to "%colored arg 2%"

command /nombre [<text>]:
	permission: skript.admin
	trigger:
		if arg 1 is not set:
			message "/nombre <texto>" to player
		if arg 1 is set:
			set the name of the player's tool to "%colored arg 1%"

command /encantar:
	permission: skript.admin
	trigger:
		enchant the player's tool with unbreaking 10

command /dañar <number>:
	permission: skript.admin
	trigger:
		damage tool by arg 1


# Comando de consola que ejecuta enjin al comprar fichas en la web
command /fichas <number> <player>:
	executable by: console
	trigger:
		log "[Inicio] %arg 2%" to "ceitiles"
		loop all items in the arg 2's inventory:
			if name of loop-item is "&e&lFicha":
				log "[Inv. pre] %arg 2% -> %loop-item%" to "ceitiles"
		wait 5 ticks
		loop arg 1 times:
			give 1 magma cream of unbreaking 10 named "&e&lFicha" with lore "&fEn &a/warp cambios&f puedes usarla." to arg 2
		wait 5 ticks
		log "%arg 2% -> Compró %arg 1% fichas en la tienda Web" to "ceitiles"
		wait 5 ticks
		message "&fSe te han entregado %arg 1% &e&lFichas&f." to arg 2
		loop all items in the arg 2's inventory:
			if name of loop-item is "&e&lFicha":
				log "[Inv. post] %arg 2% -> %loop-item%" to "ceitiles"
		log "[Fin] %arg 2%" to "ceitiles"
		stop

#Legendarias
command /legendaria [<text>] [<player>]:
	executable by: console
	trigger:
		if arg 1 is "furia":
			give a gold sword of sharpness 5 and unbreaking 3 and fire aspect 1 named {@furia} to arg 2
		if arg 1 is "arco":
			give a bow of unbreaking 3 and infinity 1 named {@arco} to the arg 2


#Comandos para crear los items
command /crear [<text>] [<player>]:
	permission: skript.admin
	trigger:
		if arg 1 is not set:
			message "Economia: ceitil - masa - bono10 - bono100 - llave - menu - seguro" to player
			message "Legendarias: furia - arco" to player
			message "Items OP: saqueadora - seda - afortunado - eficiente" to player
			message "Invocar al dragón: carne - huevo" to player
			stop
		if arg 1 is "masa":
			log "%player% -> %arg 1% -> %held item%" to "items-creados"
			set the name of the player's tool to "&c&lMasa de experiencia"
			set the 1st line of lore of the player's tool to "&fVálido por 1395 puntos de experiencia"
			set the 2nd line of lore of the player's tool to "&cNo la pierdas"
			enchant the player's tool with unbreaking 10
		if arg 1 is "bono100":
			log "%player% -> %arg 1% -> %held item%" to "items-creados"
			set the name of the player's tool to "&e&lBono de $100,000"
			set the 1st line of lore of the player's tool to "&fVéndelo en la casa de cambios"
			set the 2nd line of lore of the player's tool to "&cNo lo pierdas"
			enchant the player's tool with unbreaking 10
		if arg 1 is "bono10":
			log "%player% -> %arg 1% -> %held item%" to "items-creados"
			set the name of the player's tool to "&e&lBono de $10,000"
			set the 1st line of lore of the player's tool to "&fVéndelo en la casa de cambios"
			set the 2nd line of lore of the player's tool to "&cNo lo pierdas"
			enchant the player's tool with unbreaking 10
		if arg 1 is "menu":
			log "%player% -> %arg 1% -> %held item%" to "items-creados"
			set the name of the player's tool to "&f&lMenú &6&lOVERGY"
			set the 1st line of lore of the player's tool to "&fTus comandos a la mano."
			set the 2nd line of lore of the player's tool to "&fPuedes acceder también con &a/menu&f."
			enchant the player's tool with unbreaking 10
		if arg 1 is "llave":
			log "%player% -> %arg 1% -> %held item%" to "items-creados"
			set the name of the player's tool to "&e&lLlave de tesoro"
			set the 1st line of lore of the player's tool to "&fTe da acceso a cualquier"
			set the 2nd line of lore of the player's tool to "&ftesoro escondido en &aTierra media&f."
			enchant the player's tool with unbreaking 10
		if arg 1 is "seguro":
			log "%player% -> %arg 1% -> %held item%" to "items-creados"
			set the name of the player's tool to "&e&lSeguro para inventario"
			set the 1st line of lore of the player's tool to "&fDeja un cofre protegido con tu inventario tras tu muerte."
			enchant the player's tool with unbreaking 10
		#Armas legendarias
		if arg 1 is "furia":
			give a gold sword of sharpness 5 and unbreaking 3 and fire aspect 1 named {@furia} to the player
		if arg 1 is "arco":
			give a bow of unbreaking 3 and infinity 1 named {@arco} to the player
		#Items OP
		if arg 2 is set:
			if arg 1 is "saqueadora":
				give a diamond sword of sharpness 5 and unbreaking 3 and looting 4 named "&b&lEspada saqueadora" to arg 2
			if arg 1 is "seda":
				give a diamond pickaxe of efficiency 6 and silk touch 1 and unbreaking 3 named "&b&lPico de seda" to arg 2
			if arg 1 is "afortunado":
				give a diamond pickaxe of efficiency 5 and fortune 4 and unbreaking 3 named "&b&lPico afortunado" to arg 2
			if arg 1 is "eficiente":
				give a diamond axe of efficiency 8 and unbreaking 3 named "&b&lHacha eficiente" to arg 2
			if arg 1 is "bonoceitil":
				give a paper of unbreaking 10 named "&a&lBono para Ceitil" with lore "&fReclama un Ceitil en &a/warp cambios" to arg 2
			if arg 1 is "fragmento":
				give a lever of unbreaking 10 named "&e&lFragmento de llave del votante" with lore "&fReune 10 de estos para reclamar||&funa llave completa en &a/warp cambios" to arg 2
			if arg 1 is "rangouno":
				give 1 potion of:8193 named "&6&lRango por 1 día" with lore "&fBébela para probar un rango||&faleatorio por 1 día." to arg 2
		#invocar dragón
		if arg 1 is "carne":
			log "%player% -> %arg 1% -> %held item%" to "items-creados"
			give a rotten flesh of unbreaking 10 named "&4&lCarne del infierno" to the player
		if arg 1 is "huevo":
			log "%player% -> %arg 1% -> %held item%" to "items-creados"
			give a dragon egg of unbreaking 10 named "&e&lHuevo fértil de dragón" to the player

#Furia de los cielos
on click with sword:
	if the clicked block is set:
		if the name of the player's tool is {@furia}:
			if player has permission "skript.legendarias":
				set {_waited} to difference between {sword.%player%.lastused} and now
				if {_waited} is less than a second:
					message "&rNo abuses de tu poder."
					stop
				strike lightning effect at clicked block
				set {sword.%player%.lastused} to now
				stop
			else:
				message {@denegado} to player
				stop
on damage:
	if the name of the attacker's tool is {@furia}:
		if attacker has permission "skript.legendarias":
			set {_waited} to difference between {sword.%attacker%.lastused} and now
			if {_waited} is less than a second:
				send "&rNo abuses de tu poder." to attacker
				stop
			strike lightning effect at the victim
			add 4 to the attacker's health
			set {sword.%attacker%.lastused} to now
			stop

#Arco del fin
on projectile hit:
	if name of shooter's tool is {@arco}:
		if shooter has permission "skript.legendarias":
			wait 5 ticks
			teleport shooter to projectile
		else:
			message {@denegado} to shooter

#Carne del infierno
on death:
	victim is in "infierno":
		attacker is a player:
			chance of 10%:
				drop rotten flesh of unbreaking 10 named "&4&lCarne del infierno" at block 1 above block in front of victim
				stop


#-------------- FASE 3 -------------- 

#Taladro
# - Dar minerales en vez de menas?
#on block break:
#	if name of player's tool contains "&9&lTaladro" or "&9&lSuper taladro":
#		damage player's tool by 3
#		loop blocks in radius 1.8 of event-block:
#			if loop-block is stone or cobblestone or obsidian or any ore:
#				add loop-block to {_explosive.%player%::*}
#				loop {_explosive.%player%::*}:
#					drop loop-block
#					set loop-block to air
#					play raw sound "dig.stone" at player with pitch 1 volume 20
#					wait 3 ticks


on block break:
	if name of player's tool contains "&9&lInstaminador":
		damage player's tool by 3
		loop blocks in radius 1.8 of event-block:
			if loop-block is stone or cobblestone or obsidian or any ore:
				drop loop-block
				set loop-block to air
				play raw sound "dig.stone" at player with pitch 1 volume 20
				wait 1 ticks


#/nombre &9&lTaladro
#/lore 1 &fPica en un radio de 3 bloques.
#/lore 2 &fTriple desgaste por uso.
#/lore 3 &cNo encantable. No reparable.

# Taladora
# on break of wood:
	# if name of player's tool contains "&9&lDerribadora":
		# damage player's tool by 3
		# loop blocks upwards:
			# loop-block is wood:
				# drop the loop-block-1 at event-block
				# set the loop-block-1 to air
				# play raw sound "dig.wood" at player with pitch 1 volume 20
				# wait 3 ticks
				# loop blocks in radius 2 around loop-block:
					# if loop-block-2 is leaves or wood:
						# set the loop-block-2 to air
on break of log:
	if name of player's tool contains "&9&lDerribadora":
		damage player's tool by 3
		loop blocks upwards:
			loop-block is wood:
				drop the loop-block-1 at event-block
				set the loop-block-1 to air
				play raw sound "dig.wood" at player with pitch 1 volume 20
				wait 3 ticks
				loop blocks in radius 2 around loop-block:
					if loop-block-2 is wood:
						drop the loop-block-2 at loop-block-2
						set the loop-block-2 to air
					if loop-block-2 is leaves:
						set the loop-block-2 to air
on break of dark oak wood:
	if name of player's tool contains "&9&lDerribadora":
		damage player's tool by 3
		loop blocks upwards:
			loop-block is dark oak wood:
				drop the loop-block-1 at event-block
				set the loop-block-1 to air
				play raw sound "dig.wood" at player with pitch 1 volume 20
				wait 3 ticks
				loop blocks in radius 2 around loop-block:
					if loop-block-2 is dark oak wood:
						drop the loop-block-2 at loop-block-2
						set the loop-block-2 to air
					if loop-block-2 is dark oak leaves:
						set the loop-block-2 to air

#/nombre &9&lTaladora
#/lore 1 &fTala todo el tronco del árbol.
#/lore 2 &fTriple desgaste por uso.
#/lore 3 &cNo encantable. No reparable.


#---------   No reparar   ---------#
on command "/repair":
	if player don't have the permission "skript.admin":
		if name of player's tool contains "&9&lInstaminador" or "&9&lDerribadora":
			cancel event
			message "&cNo puedes reparar esta herramienta."

#---------   No encantar   ---------#
on enchant:  
	if name of event-item contains "&9&lInstaminador" or "&9&lDerribadora":
		cancel event
		message "&cNo puedes encantar esta herramienta."
						
						