every 10 seconds:
	broadcast "CPUs: %available processors%"
	broadcast "Uso de CPU: %cpu usage%"
	broadcast "Ip: %server ip%"
	broadcast "Puerto: %server port%"
	broadcast "Tiempo del sv: %server up-time%"
	broadcast "Distancia de chunks: %view distance%"
	broadcast "Memoria total: %total memory in mb% MB"
	broadcast "Máxima memoria: %max memory in mb% MB"
	broadcast "Memoria libre: %free memory in mb% MB"
	stop
