on command "/warp":
	if "%arguments%" is "infierno":
		cancel event
		message "&e&lInfierno en mantenimiento, podrás volver a él en contados minutos." to player
		
command /infiernosacar:
	permission: skript.admin
	trigger:
		loop players in "infierno":
			execute console command "/mv tp %loop-player% tierramedia"

on player teleport:
	wait 5 ticks
	player is in "infierno"
	player don't have the permission "skript.admin"
	execute console command "/mv tp %player% tierramedia"
	